/* ===================== games data ===================== */
const PUZZLES = [
  {art: "heart", lvl: "easy"}, {art: "crown", lvl: "easy"}, {art: "tree", lvl: "easy"},
  {art: "flower", lvl: "easy"}, {art: "balloon", lvl: "easy"}, {art: "moon", lvl: "easy"},
  {art: "smile", lvl: "medium"}, {art: "house", lvl: "medium"}, {art: "fish", lvl: "medium"},
  {art: "sun", lvl: "medium"}, {art: "car", lvl: "medium"}, {art: "cake", lvl: "medium"},
  {art: "rocket", lvl: "hard"}, {art: "butterfly", lvl: "hard"}, {art: "cat", lvl: "hard"},
  {art: "rainbow", lvl: "hard"}, {art: "gift", lvl: "hard"}, {art: "planet", lvl: "hard"},
];
const LEVEL_AGES = {easy: ["Ages 5+", "من 5 سنوات"], medium: ["Ages 7+", "من 7 سنوات"], hard: ["Ages 9+", "من 9 سنوات"]};
const TRACE = {
  en: [["A","Apple","🍎"],["B","Ball","⚽"],["C","Cat","🐱"],["D","Duck","🦆"],["E","Egg","🥚"],["F","Fish","🐟"],
       ["G","Grapes","🍇"],["H","Hat","🎩"],["I","Ice cream","🍦"],["J","Juice","🧃"],["K","Kite","🪁"],["L","Lion","🦁"],
       ["M","Moon","🌙"],["N","Nut","🥜"],["O","Orange","🍊"],["P","Pizza","🍕"],["Q","Queen","👑"],["R","Rainbow","🌈"],
       ["S","Sun","☀️"],["T","Tree","🌳"],["U","Umbrella","☂️"],["V","Violin","🎻"],["W","Whale","🐳"],["X","Xylophone","🎹"],
       ["Y","Yo-yo","🪀"],["Z","Zebra","🦓"]],
  ar: [["ا","أرنب","🐰"],["ب","بطة","🦆"],["ت","تفاحة","🍎"],["ث","ثعلب","🦊"],["ج","جمل","🐫"],["ح","حصان","🐴"],
       ["خ","خروف","🐑"],["د","دب","🐻"],["ذ","ذرة","🌽"],["ر","راديو","📻"],["ز","زرافة","🦒"],["س","سمكة","🐟"],
       ["ش","شمس","☀️"],["ص","صاروخ","🚀"],["ض","ضفدع","🐸"],["ط","طائرة","✈️"],["ظ","ظرف","✉️"],["ع","عنب","🍇"],
       ["غ","غيمة","☁️"],["ف","فيل","🐘"],["ق","قمر","🌙"],["ك","كعكة","🎂"],["ل","ليمون","🍋"],["م","موز","🍌"],
       ["ن","نحلة","🐝"],["ه","هدية","🎁"],["و","وردة","🌹"],["ي","يد","✋"]],
};
const SPELL = {
  en: [["CAT","🐱"],["DOG","🐶"],["SUN","☀️"],["BEE","🐝"],["BUS","🚌"],["EGG","🥚"],["HAT","🎩"],
       ["FISH","🐟"],["STAR","⭐"],["CAKE","🎂"],["BALL","⚽"],["MOON","🌙"],["FROG","🐸"],["DUCK","🦆"],["TREE","🌳"],["LION","🦁"],
       ["APPLE","🍎"],["HOUSE","🏠"],["TRAIN","🚆"],["ROBOT","🤖"]],
  ar: [["قطة","🐱"],["شمس","☀️"],["بطة","🦆"],["قمر","🌙"],["كرة","⚽"],["بيت","🏠"],["أسد","🦁"],
       ["نحلة","🐝"],["سمكة","🐟"],["كعكة","🎂"],["شجرة","🌳"],["نجمة","⭐"],["قطار","🚆"],["وردة","🌹"],["تفاحة","🍎"]],
};
const AR_LETTERS = "ابتثجحخدذرزسشصضطظعغفقكلمنهوي";

addStrings({
  modeFree: ["Free build", "بناء حر"], modeCopy: ["Copy it", "انسخ الصورة"], modeTrace: ["Trace letters", "تتبّع الحروف"],
  modeSpell: ["Spell it", "تهجئة"], modeMath: ["Brick math", "حساب المكعبات"],
  playModes: ["Play modes", "طرق اللعب"],
  copyTitle: ["Copy the {n}", "انسخ: {n}"],
  copyText_easy: ["Cover the faint colors with bricks of the same color.", "غطِّ الألوان الباهتة بمكعبات من نفس اللون."],
  copyText_medium: ["Fill the dashed spots. Look at the picture to pick the colors!", "املأ الأماكن المنقّطة. انظر إلى الصورة لتختار الألوان!"],
  copyText_hard: ["Build the picture in the middle of the board, all by yourself!", "ابنِ الصورة في وسط اللوحة وحدك!"],
  progStuds: ["{a} of {b} spots right", "{a} من {b} صحيحة"],
  hint: ["Hint", "تلميح"], startOver: ["Start over", "من جديد"], levels: ["Levels", "المراحل"], next: ["Next", "التالي"],
  hintSay: ["The blinking spots need fixing.", "الأماكن التي تومض تحتاج إلى تصحيح."],
  copyWin: ["You copied the {n}! {s}", "نسخت {n}! {s}"],
  easy: ["Easy", "سهل"], medium: ["Medium", "متوسط"], hard: ["Hard", "صعب"],
  pickPicture: ["Pick a picture", "اختر صورة"],
  traceTitle: ["Trace the letter {l}", "تتبّع الحرف {l}"],
  traceText: ["Cover every dashed spot with bricks.", "غطِّ كل الأماكن المنقّطة بالمكعبات."],
  traceWin: ["{l} is for {w}!", "{l} كما في {w}!"],
  progCover: ["{a} of {b} covered", "غطّيت {a} من {b}"],
  pickLetter: ["Pick a letter", "اختر حرفًا"],
  spellTitle: ["Spell the word", "تهجَّ الكلمة"],
  spellText: ["Tap the letters in the right order.", "اضغط على الحروف بالترتيب الصحيح."],
  spellWrong: ["Not that one. Try again!", "ليس هذا. حاول مرة أخرى!"],
  spellWin: ["You spelled {w}! {s}", "تهجّيت {w}! {s}"],
  progLetters: ["{a} of {b} letters", "{a} من {b} حروف"],
  hintSpell: ["The next letter is {l}.", "الحرف التالي هو {l}."],
  pickWord: ["Pick a word", "اختر كلمة"],
  mathTitle: ["Make {n}!", "كوّن {n}!"],
  mathText: ["Put bricks on the board until there are exactly {n} bumps.", "ضع مكعبات حتى يصبح عدد النتوءات {n} بالضبط."],
  mathTextK: ["Use exactly {k} bricks to make {n} bumps.", "استخدم {k} مكعبات بالضبط لتكوّن {n} نتوءًا."],
  mathTooMany: ["Too many! Take some bricks off.", "أكثر من اللازم! أزِل بعض المكعبات."],
  mathBricks: ["Right number! Now use exactly {k} bricks.", "العدد صحيح! الآن استخدم {k} مكعبات بالضبط."],
  mathWin: ["Yes! {eq}", "أحسنت! {eq}"],
  mathLevel: ["Level {n}", "المرحلة {n}"],
  hintMath: ["Count the bumps on each brick. A 2×2 brick has 4.", "عُدّ النتوءات على كل مكعب. المكعب 2×2 فيه 4."],
  bumps: ["bumps", "نتوءات"],
  freeBack: ["Back to free building!", "عدنا إلى البناء الحر!"],
  gameStart: ["Let's play! {t}", "هيا نلعب! {t}"],
  letterSet: ["Letters", "الحروف"],
});
