/* ===================== data ===================== */
// smallest first: names grow through this list in order until they fit
const SIZES = [
  {id: "t", en: "Tiny",   ar: "صغيرة جدًا", cols: 12, rows: 9},
  {id: "s", en: "Small",  ar: "صغيرة", cols: 16, rows: 12},
  {id: "m", en: "Medium", ar: "وسط",   cols: 24, rows: 18},
  {id: "q", en: "Square", ar: "مربعة", cols: 24, rows: 24},
  {id: "l", en: "Large",  ar: "كبيرة", cols: 32, rows: 24},
  {id: "w", en: "Wide",   ar: "عريضة", cols: 48, rows: 24},
  {id: "x", en: "Huge",   ar: "ضخمة",  cols: 40, rows: 30},
  {id: "g", en: "Mega",   ar: "عملاقة", cols: 56, rows: 42},
];
// the Poster board belongs to Brick my photo only: it never shows in the board size picker,
// and clearing it or starting a new board goes back to a normal size
const PHOTO_SIZES = [
  {id: "p", en: "Poster", ar: "ملصق",   cols: 96, rows: 72},
];
const ALL_SIZES = SIZES.concat(PHOTO_SIZES);
const PLATES = [
  {en: "Pink",   ar: "وردية",   hex: "#FF2E8A"},
  {en: "Blue",   ar: "زرقاء",   hex: "#2F9BF0"},
  {en: "Green",  ar: "خضراء",   hex: "#3DC45A"},
  {en: "Purple", ar: "بنفسجية", hex: "#8F7FEA"},
  {en: "Yellow", ar: "صفراء",   hex: "#FFD23F"},
  {en: "White",  ar: "بيضاء",   hex: "#F2EFF7"},
  {en: "Night",  ar: "ليلية",   hex: "#27336B"},
  {en: "Sand",   ar: "رملية",   hex: "#EFC98B"},
];
const COLORS = [
  {en: "White",      ar: "أبيض",       hex: "#FBFAF5"},
  {en: "Light pink", ar: "وردي فاتح",  hex: "#FFB3CF"},
  {en: "Mint",       ar: "نعناعي",     hex: "#7FE3C0"},
  {en: "Lavender",   ar: "خزامى",      hex: "#A9A6F0"},
  {en: "Yellow",     ar: "أصفر",       hex: "#FFE838"},
  {en: "Hot pink",   ar: "وردي غامق",  hex: "#FF2E8A"},
  {en: "Red",        ar: "أحمر",       hex: "#F2383A"},
  {en: "Orange",     ar: "برتقالي",    hex: "#FF9A1F"},
  {en: "Green",      ar: "أخضر",       hex: "#3DC45A"},
  {en: "Blue",       ar: "أزرق",       hex: "#2F8CF0"},
  {en: "Sky",        ar: "سماوي",      hex: "#8FD3FF"},
  {en: "Purple",     ar: "بنفسجي",     hex: "#8A4DE0"},
  {en: "Tan",        ar: "حنطي",       hex: "#E3A878"},
  {en: "Brown",      ar: "بني",        hex: "#9A5B34"},
  {en: "Gray",       ar: "رمادي",      hex: "#9AA0AE"},
  {en: "Black",      ar: "أسود",       hex: "#2E2A3A"},
];
const STYLES = [
  {id: "std",     en: "Classic", ar: "كلاسيك"},
  {id: "glitter", en: "Glitter", ar: "بريق"},
  {id: "glow",    en: "Glow",    ar: "مضيء"},
  {id: "neon",    en: "Neon",    ar: "نيون"},
  {id: "light",   en: "Light",   ar: "فاتح"},
  {id: "jelly",   en: "Jelly",   ar: "جيلي"},
  {id: "candy",   en: "Candy",   ar: "حلوى"},
  {id: "rainbow", en: "Rainbow", ar: "قوس قزح"},
  {id: "pixel",   en: "Pixel",   ar: "بكسل"},
  {id: "ice",     en: "Ice",     ar: "ثلج"},
];
// long side first (lying down)
const SHAPES = [[1,1],[2,2],[3,2],[4,2]];
const PAL = {R:"#F2383A",W:"#FBFAF5",Y:"#FFE838",K:"#2E2A3A",P:"#FFB3CF",G:"#3DC45A",B:"#2F8CF0",O:"#FF9A1F",
             M:"#7FE3C0",L:"#A9A6F0",H:"#FF2E8A",V:"#8A4DE0",N:"#9A5B34",S:"#8FD3FF",A:"#9AA0AE"};
const ART = {
  heart:    {en: "Heart",     ar: "قلب",       art: ".RR.RR.|RWRRRRR|RRRRRRR|.RRRRR.|..RRR..|...R..."},
  star:     {en: "Star",      ar: "نجمة",      art: "...Y...|...Y...|YYYYYYY|.YYYYY.|..YYY..|.YY.YY.|.Y...Y."},
  smile:    {en: "Smiley",    ar: "وجه مبتسم", art: ".YYYYY.|YYYYYYY|YKYYYKY|YYYYYYY|YKYYYKY|YYKKKYY|.YYYYY."},
  flower:   {en: "Flower",    ar: "زهرة",      art: ".W.W.|WWYWW|.WWW.|..G..|GGG..|..GGG|..G.."},
  crown:    {en: "Crown",     ar: "تاج",       art: "Y.Y.Y|YYYYY|YRYBY|YYYYY"},
  house:    {en: "House",     ar: "بيت",       art: "...R...|..RRR..|.RRRRR.|RRRRRRR|.WWWWW.|.WBWNW.|.WWWNW."},
  tree:     {en: "Tree",      ar: "شجرة",      art: "..G..|.GGG.|GGGGG|.GGG.|GGGGG|..N..|..N.."},
  sun:      {en: "Sun",       ar: "شمس",       art: "Y..Y..Y|.YOOOY.|.OOOOO.|YOOOOOY|.OOOOO.|.YOOOY.|Y..Y..Y"},
  fish:     {en: "Fish",      ar: "سمكة",      art: "....OOO.|O..OOOOO|OOOOOOKO|O..OOOOO|....OOO."},
  cat:      {en: "Cat",       ar: "قطة",       art: "K.....K|KK...KK|KKKKKKK|KYKKKYK|KKKPKKK|.KKKKK.|..KKK.."},
  rocket:   {en: "Rocket",    ar: "صاروخ",     art: "..R..|.RWR.|.WWW.|.WBW.|.WWW.|.WWW.|RWWWR|R.O.R|..Y.."},
  rainbow:  {en: "Rainbow",   ar: "قوس قزح",   art: "..RRRRR..|.ROOOOOR.|ROYYYYYOR|OYGGGGGYO|YG.....GY"},
  car:      {en: "Car",       ar: "سيارة",     art: "..BBBB..|.BSBBSB.|BBBBBBBB|BBBBBBYB|.KK..KK."},
  butterfly:{en: "Butterfly", ar: "فراشة",     art: "VV...VV|VPVKVPV|VVVKVVV|.VVKVV.|VPVKVPV|VV...VV"},
  planet:   {en: "Planet",    ar: "كوكب",      art: "..OOO..|.OOOOO.|LLLLLLL|.OOOOO.|..OOO.."},
  alien:    {en: "Alien",     ar: "فضائي",     art: ".G...G.|..GGG..|.GGGGG.|GKGGGKG|GGGGGGG|.G.G.G."},
  moon:     {en: "Moon",      ar: "هلال",      art: "..YYY|.YY..|YY...|YY...|YY...|.YY..|..YYY"},
  cake:     {en: "Cake",      ar: "كعكة",      art: ".Y.Y.Y.|.R.R.R.|PPPPPPP|WWWWWWW|PPPPPPP|HWHWHWH"},
  balloon:  {en: "Balloon",   ar: "بالون",     art: ".RRR.|RRRRR|RWRRR|RRRRR|.RRR.|..R..|..K..|.K..."},
  gift:     {en: "Gift",      ar: "هدية",      art: "..Y.Y..|...Y...|BBBYBBB|BBBYBBB|YYYYYYY|BBBYBBB"},
  lantern:  {en: "Lantern",   ar: "فانوس",     art: "..Y..|.YYY.|YOOOY|YOYOY|YOOOY|YOYOY|.YYY.|..Y.."},
  mosque:   {en: "Mosque",    ar: "مسجد",      art: "....Y....|...WWW...|..WWWWW..|.WWWWWWW.|WWWWWWWWW|WW.W.W.WW|WWWWWWWWW"},
  octopus:  {en: "Octopus",   ar: "أخطبوط",    art: ".VVVVV.|VVVVVVV|VKVVVKV|VVVVVVV|V.V.V.V|V.V.V.V|.V...V."},
  starfish: {en: "Starfish",  ar: "نجم البحر", art: "...O...|...O...|OOOOOOO|.OOOOO.|..OOO..|.OO.OO.|.O...O."},
};
const BASE_STAMPS = ["heart", "star", "smile", "flower", "crown", "house", "tree"];
const THEMES = {
  classic:  {en: "Classic",  ar: "كلاسيك",  plate: "#FF2E8A", stamps: []},
  space:    {en: "Space",    ar: "الفضاء",  plate: "#27336B", stamps: ["rocket", "planet", "alien", "moon"]},
  sea:      {en: "Sea",      ar: "البحر",   plate: "#2F9BF0", stamps: ["fish", "octopus", "starfish"]},
  birthday: {en: "Birthday", ar: "عيد ميلاد", plate: "#8F7FEA", stamps: ["cake", "balloon", "gift"]},
  eid:      {en: "Eid",      ar: "العيد",   plate: "#3DC45A", stamps: ["moon", "lantern", "mosque"]},
};
const FONT = {
  A:".##.|#..#|####|#..#|#..#", B:"###.|#..#|###.|#..#|###.", C:".###|#...|#...|#...|.###",
  D:"###.|#..#|#..#|#..#|###.", E:"####|#...|###.|#...|####", F:"####|#...|###.|#...|#...",
  G:".###|#...|#.##|#..#|.###", H:"#..#|#..#|####|#..#|#..#", I:"###|.#.|.#.|.#.|###",
  J:"..##|...#|...#|#..#|.##.", K:"#..#|#.#.|##..|#.#.|#..#", L:"#...|#...|#...|#...|####",
  M:"#...#|##.##|#.#.#|#...#|#...#", N:"#...#|##..#|#.#.#|#..##|#...#", O:".##.|#..#|#..#|#..#|.##.",
  P:"###.|#..#|###.|#...|#...", Q:".##.|#..#|#..#|#.#.|.#.#", R:"###.|#..#|###.|#.#.|#..#",
  S:".###|#...|.##.|...#|###.", T:"#####|..#..|..#..|..#..|..#..", U:"#..#|#..#|#..#|#..#|.##.",
  V:"#...#|#...#|.#.#.|.#.#.|..#..", W:"#...#|#...#|#.#.#|##.##|#...#", X:"#...#|.#.#.|..#..|.#.#.|#...#",
  Y:"#...#|.#.#.|..#..|..#..|..#..", Z:"####|...#|.##.|#...|####",
  "0":"###|#.#|#.#|#.#|###", "1":".#.|##.|.#.|.#.|###", "2":"###.|...#|.##.|#...|####",
  "3":"###.|...#|.##.|...#|###.", "4":"#..#|#..#|####|...#|...#", "5":"####|#...|###.|...#|###.",
  "6":".##.|#...|###.|#..#|.##.", "7":"####|...#|..#.|.#..|.#..", "8":".##.|#..#|.##.|#..#|.##.",
  "9":".##.|#..#|.###|...#|.##.",
  "♥":".#.#.|#####|#####|.###.|..#..", "★":"..#..|.###.|#####|.###.|.#.#.",
  "!":"#|#|#|.|#", "?":"###.|...#|.##.|....|.#..", ".":".|.|.|.|#", "-":"...|...|###|...|...", "'":"#|#|.|.|.",
};
const RAINBOW = ["#F2383A", "#FF9A1F", "#FFE838", "#3DC45A", "#2F8CF0", "#8A4DE0"];
const CANDY   = ["#FBFAF5", "#7FE3C0", "#A9A6F0", "#FFE838", "#FFB3CF"];
const LOGO_COLORS = ["#FF2E8A", "#FFE838", "#7FE3C0", "#FBFAF5", "#A9A6F0", "#FF9A1F"];

/* ===================== words (English / Arabic) ===================== */
const STR = {en: {}, ar: {}};
function addStrings(pairs){ for (const k in pairs){ STR.en[k] = pairs[k][0]; STR.ar[k] = pairs[k][1]; } }
addStrings({
  appName: ["Snappy Bricks", "مكعبات سنابي"],
  talkOn: ["Talking on", "الكلام مفعّل"], talkOff: ["Talking off", "الكلام متوقف"],
  soundOn: ["Sound on", "الصوت مفعّل"], soundOff: ["Sound off", "الصوت متوقف"],
  pickColor: ["Pick a color", "اختر لونًا"],
  brickStyle: ["Brick style", "نوع المكعب"],
  dragBrick: ["Drag a brick", "اسحب مكعبًا"],
  dragHint: ["Drag it to the board, or tap it and then tap the board.", "اسحبه إلى اللوحة، أو اضغط عليه ثم اضغط على اللوحة."],
  turnBricks: ["Turn bricks", "لُفّ المكعبات"],
  funShapes: ["Fun shapes", "أشكال ممتعة"],
  paint: ["Paint", "تلوين"], fill: ["Fill", "تعبئة"], eraser: ["Eraser", "ممحاة"],
  tt_paint: ["Tap or swipe over bricks to color them", "اضغط أو مرّر على المكعبات لتلوينها"],
  tt_fill: ["Fill an empty space, or recolor a whole shape", "املأ مكانًا فارغًا، أو غيّر لون شكل كامل"],
  tt_draw: ["Draw with your finger to make bricks", "ارسم بإصبعك لتصنع مكعبات"],
  tt_play: ["Watch Bricky play on your build", "شاهد بريكي يلعب على بنائك"],
  draw: ["Draw", "ارسم"], play: ["Play", "العب"],
  tt_erase: ["Tap or swipe over bricks to take them off", "اضغط أو مرّر على المكعبات لإزالتها"],
  tt_stack: ["Stack bricks on top of each other", "ضع المكعبات فوق بعضها"],
  tt_clear: ["Clear the board", "امسح اللوحة"],
  stack: ["Stack", "تكديس"],
  undo: ["Undo", "تراجع"], clear: ["Clear", "مسح"], sure: ["Sure?", "متأكد؟"],
  savePicture: ["Save picture", "احفظ الصورة"],
  dropTrash: ["Drop here to throw away", "أفلت هنا للرمي"],
  writeName: ["Write my name", "اكتب اسمي"],
  namePh: ["Your name here", "اسمك هنا"],
  addHeart: ["Add a heart", "أضف قلبًا"], addStar: ["Add a star", "أضف نجمة"],
  letterColors: ["Letter colors", "ألوان الحروف"],
  rainbow: ["Rainbow", "قوس قزح"], candy: ["Candy", "حلوى"], myColor: ["My color", "لوني"],
  buildName: ["Build my name!", "ابنِ اسمي!"],
  board: ["Board", "اللوحة"], size: ["Size", "الحجم"], boardColor: ["Board color", "لون اللوحة"],
  boardStyle: ["Board style", "نوع اللوحة"],
  plateStyleSay_std: ["A classic board with bumps on top.", "لوحة كلاسيكية بنتوءات صغيرة."],
  plateStyleSay_glitter: ["A sparkly glitter board!", "لوحة لامعة بالبريق!"],
  plateStyleSay_glow: ["A glow board that shines like a magic light!", "لوحة مضيئة تلمع مثل ضوء سحري!"],
  plateStyleSay_neon: ["A neon board that lights up like a sign at night!", "لوحة نيون تضيء مثل لافتة في الليل!"],
  plateStyleSay_light: ["A light board full of little lamps!", "لوحة فاتحة مليئة بالمصابيح الصغيرة!"],
  plateStyleSay_jelly: ["A wobbly jelly board, like a big gummy sweet!", "لوحة جيلي تهتز مثل حلوى جيلي كبيرة!"],
  plateStyleSay_candy: ["A candy board, like a cake with sprinkles!", "لوحة حلوى مثل كعكة عليها حبيبات ملونة!"],
  plateStyleSay_rainbow: ["A rainbow board full of colors!", "لوحة قوس قزح مليئة بالألوان!"],
  plateStyleSay_pixel: ["A pixel board, like a video game screen!", "لوحة بكسل مثل شاشة لعبة فيديو!"],
  plateStyleSay_ice: ["An ice board, like a frozen pond!", "لوحة ثلج مثل بركة متجمدة!"],
  undone: ["Undone! It's back the way it was.", "تم التراجع! عاد كما كان."],
  oneBrick: ["1 brick", "المكعبات: 1"], nBricks: ["{n} bricks", "المكعبات: {n}"],
  builtWith: ["Built with Snappy Bricks", "صُنعت بمكعبات سنابي"],
  paintReady: ["{c} paint is ready. Tap or swipe over bricks!", "اللون {c} جاهز. اضغط أو مرّر على المكعبات!"],
  drawReady: ["{c} pencil is ready. Draw on the board!", "قلم {c} جاهز. ارسم على اللوحة!"],
  colorPicked: ["{c} it is! Now drag a brick.", "اخترت {c}! الآن اسحب مكعبًا."],
  styleSay_std: ["Classic bricks with bumps on top.", "مكعبات كلاسيكية بنتوءات صغيرة."],
  styleSay_glitter: ["Sparkly glitter bricks!", "مكعبات لامعة بالبريق!"],
  styleSay_glow: ["Glow bricks shine like magic lights!", "مكعبات مضيئة تلمع مثل الأضواء السحرية!"],
  styleSay_light: ["Light bricks shine like little lamps!", "مكعبات فاتحة تضيء مثل المصابيح الصغيرة!"],
  styleSay_neon: ["Neon bricks light up like signs at night!", "مكعبات النيون تضيء مثل اللافتات في الليل!"],
  styleSay_jelly: ["Jelly bricks wobble like gummy sweets!", "مكعبات الجيلي تهتز مثل حلوى الجيلي!"],
  styleSay_candy: ["Candy bricks with sweet stripes!", "مكعبات حلوى بخطوط لذيذة!"],
  styleSay_rainbow: ["Rainbow bricks in every color!", "مكعبات قوس قزح بكل الألوان!"],
  styleSay_pixel: ["Pixel bricks, like in a video game!", "مكعبات بكسل مثل لعبة فيديو!"],
  styleSay_ice: ["Frosty ice bricks with snowflakes!", "مكعبات ثلج باردة عليها ندف الثلج!"],
  brickAria: ["{s} brick", "مكعب {s}"],
  tapToPlace: ["Now tap the board to put it there. Tap it again to stop.", "الآن اضغط على اللوحة لتضعه. اضغط عليه مرة أخرى للتوقف."],
  dragAnytime: ["Okay! Drag a brick onto the board whenever you like.", "حسنًا! اسحب مكعبًا إلى اللوحة متى شئت."],
  tool_paint: ["Paint: tap or swipe over bricks to color them.", "تلوين: اضغط أو مرّر على المكعبات لتلوينها."],
  tool_fill: ["Fill: tap an empty space to fill it, or tap a shape to recolor it.", "تعبئة: اضغط على مكان فارغ لتملأه، أو على شكل لتغيّر لونه."],
  tool_draw: ["Draw: draw with your finger and it turns into bricks! Draw a circle to fill it in.", "ارسم: ارسم بإصبعك وسيتحوّل الرسم إلى مكعبات! ارسم دائرة لتمتلئ."],
  playStart: ["Watch me play on your build! Can I reach all the stars?", "شاهدني ألعب على بنائك! هل أصل إلى كل النجوم؟"],
  playEmpty: ["Build me something to climb on first!", "ابنِ لي شيئًا أتسلّق عليه أولًا!"],
  playWin: ["I got all the stars! Thank you for building me a playground!", "جمعت كل النجوم! شكرًا لأنك بنيت لي ملعبًا!"],
  playBye: ["That was fun! Build me higher steps and press Play again.", "كان ذلك ممتعًا! ابنِ لي درجات أعلى واضغط العب مرة أخرى."],
  tool_erase: ["Eraser: tap or swipe over bricks to take them off.", "ممحاة: اضغط أو مرّر على المكعبات لإزالتها."],
  stackOn: ["Stacking is on. Drop bricks on top of other bricks!", "التكديس مفعّل. ضع المكعبات فوق بعضها!"],
  stackOff: ["Stacking is off. Bricks go on the board only.", "التكديس متوقف. المكعبات توضع على اللوحة فقط."],
  cheers: ["Snap!|Nice one!|Looking great!|Click! Perfect fit.|You're a builder!", "طَق!|رائع!|يبدو جميلًا!|تمام! مكانه مضبوط.|أنت بنّاء ماهر!"],
  tooHigh: ["That tower is as tall as it can go!", "هذا البرج وصل إلى أعلى ارتفاع!"],
  spotTaken: ["Oops, that spot is taken. Find an empty spot, or turn on Stack.", "عذرًا، هذا المكان مشغول. ابحث عن مكان فارغ، أو فعّل التكديس."],
  byeBrick: ["Bye bye, brick!", "وداعًا يا مكعب!"],
  squareTurn: ["Square bricks look the same when you turn them!", "المكعبات المربعة تبقى كما هي عندما تلفّها!"],
  noRoomTurn: ["No room to turn it here. Try moving it first.", "لا يوجد مكان للفّه هنا. جرّب تحريكه أولًا."],
  tapHint: ["Drag a brick here from the tray, or tap one first and then tap here.", "اسحب مكعبًا إلى هنا، أو اضغط عليه أولًا ثم اضغط هنا."],
  noRoomThere: ["No room right there. Try an empty spot!", "لا يوجد مكان هنا. جرّب مكانًا فارغًا!"],
  turnedUp: ["Bricks are standing up tall now.", "المكعبات واقفة الآن."],
  turnedDown: ["Bricks are lying down again.", "المكعبات مستلقية من جديد."],
  clearAgain: ["Tap Clear again to take every brick off.", "اضغط مسح مرة أخرى لإزالة كل المكعبات."],
  allClear: ["All clear! Tap Undo if you want it back.", "اللوحة فارغة! اضغط تراجع إن أردت استرجاعها."],
  alreadyEmpty: ["The board is already empty. Time to build!", "اللوحة فارغة. هيا نبني!"],
  holdToSave: ["Here's your picture! Press and hold it (or right-click) to save it.", "هذه صورتك! اضغط عليها مطولًا (أو بالزر الأيمن) لحفظها."],
  close: ["Close", "إغلاق"], yourPicture: ["Your picture", "صورتك"],
  buildFirst: ["Build something first, then save a picture of it!", "ابنِ شيئًا أولًا، ثم احفظ صورته!"],
  savedPic: ["Saved! Show your picture to someone special.", "تم الحفظ! أرِ صورتك لشخص تحبه."],
  noPic: ["Okay, no picture this time.", "حسنًا، لا صورة هذه المرة."],
  picReady: ["Your picture is ready!", "صورتك جاهزة!"],
  plateSay: ["A {c} board. Pretty!", "لوحة {c}. جميلة!"],
  sizeCut: ["Some bricks didn't fit on the smaller board. Tap Undo to bring them back.", "بعض المكعبات لم تتسع في اللوحة الأصغر. اضغط تراجع لإرجاعها."],
  sizeSay: ["{s} board: {c} × {r} studs.", "لوحة {s}: {c} × {r}."],
  typeFirst: ["Type your name in the box first!", "اكتب اسمك في المربع أولًا!"],
  tooLong: ["That's too long for the board. Try a shorter word!", "هذا طويل على اللوحة. جرّب كلمة أقصر!"],
  nameWow: ["Wow, {n}! Great building!", "واو، {n}! بناء رائع!"],
  langSay: ["Hello! Let's build together.", "أهلًا! هيا نبني معًا."],
  hello: ["Hi! Drag a brick onto the board, or write your name.", "مرحبًا! اسحب مكعبًا إلى اللوحة، أو اكتب اسمك."],
  welcomeBack: ["Welcome back! Your board is just how you left it.", "أهلًا بعودتك! لوحتك كما تركتها."],
  talkSayOn: ["I'll read letters and words out loud.", "سأقرأ الحروف والكلمات بصوت عالٍ."],
  talkSayOff: ["Okay, I'll stay quiet.", "حسنًا، سأبقى هادئًا."],
  tipTwoFinger: ["Tip: while you drag a long brick, tap the screen with another finger to turn it!", "نصيحة: أثناء سحب مكعب طويل، اضغط على الشاشة بإصبع آخر لتلفّه!"],
  noArabicVoice: ["This device has no Arabic voice, so I'll read in English only.", "هذا الجهاز لا يملك صوتًا عربيًا، لذلك سأقرأ بالإنجليزية فقط."],
});
